version: '3.3'

services:
  app:
    image: fresque-maps
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
    restart: always

  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    ports:
      - '5434:5432'
    volumes:
      - fresque-maps-pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  fresque-maps-pgdata:
